### PR TITLE
Issue #6

### LINKED ISSUE #6: "This Module is configured to show dynamic Data. Please use Modulesettings to change"
Where, exactly, can you change this text, if at all? The only place I can find is in EditLinks.ascx, which is suboptimal. There's no place in the module settings that I can find that allows you to change (or add) any sort of text to the module.

Our use case is that we'd like to replace that line of text with some instructions ("PDFs only", that sort of thing).

### PR DESCRIPTION
**Pull request by trouble2**
Hi there, My first attempt of working with github, so if I make any mistakes...sorry....
Just let me know what to do...

## Please mark which issue is solved

Close #6

### CODE REVIEW

**Comment by valadas** [comment]
@trouble2 I wanted to make a video on how to submit pull requests here, is it ok with you if I use this example for a before/after video? I was looking for something simple to not overcomplicate the video and this would be a good example. Let me know, thanks.

**Comment by trouble2** [comment]
Sure go ahead.
I tried to use nuget but it said it couldn't find the specific version, so instead I referenced my local files.
This is also what is said in the documentation by the way, so perhaps that should be modified (https://github.com/DNNCommunity/home/wiki/Setting-Up-your-DNN-Extensions-Development-Environment)

**Comment by EPTamminga** [comment]
@trouble2
I made a note on the page you mentioned and wrote that the instruction will (have to) be updated

**Comment by valadas** [comment]
@trouble2 when just before creating the commit, you can select what files will be included in the commit, that way you can skip files that where modified for local build. But I will investigate the Nuget issue, it has worked if I remember correctly on a vanilla Visual Studio installation in my tests, but I know some versions are only on MyGet. I'll check that. Please allow me a day or two since I am a bit busy for the next days, but I will create some better instructions and use this pull request as an example.

**Comment by trouble2** [comment]
Sure, no worries.
I've also tried the announcements module, and this worked without a problem, so perhaps you can compare the two for differences.

**Comment by valadas** [comment]
Ok, I have used this to create a video, I will leave this open until I upload the video so I can link to it here but the localization change was made in pull request #23

**Comment by valadas** [comment]
I will also go fix the dll references

**Comment by valadas** [comment]
Ok, I have fixed the build issues with #25 but I did not publish the video yet, it was too long and I recorded a few mistakes. So basically, everything that was in this pull request is now solved and I will publish a new video next week about what I wanted to show.

**Pull request closed without merging**
